export default {
  SEARCH_COUNTRIES: 'countries/SEARCH_COUNTRIES',
  SEARCH_COUNTRIES_SUCCESS: 'countries/SEARCH_COUNTRIES_SUCCESS',
  SEARCH_COUNTRIES_FAILED: 'countries/SEARCH_COUNTRIES_FAILED',
  SET_CURRENT_COUNTRY: 'countries/SET_CURRENT_COUNTRY',
};
